language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - mv dummy_keys.py keys.py
  - python main.py
  - python graphing/csv_grapher.py
  - python logging/stat_logger.py
